sudo: required
services:
    - docker
 
before_install:
    - docker build -t jobitg/docker-react -f dockerfile.dev .
   
script:
    - docker run jobitg/docker-react npm run test -- --coverage
    
deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket-name: "elasticbeanstalk-eu-west-1-699251366609"
    bucket-path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"