sudo: required
services:
    - docker
 
 before_install:
    - docker build -t jobitg/docker-react -f Dockerfile.dev .
   
 Scripts:
    - docker run jobitg/docker-react npm run test -- --coverage
    
    